name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          SHOW_TOTAL: true
          LANG_COUNT: 10
          STOP_AT_OTHER: true
          CODE_LANG: python
